language: java

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk9
  - oraclejdk9
  - openjdk10
  - oraclejdk10
  - openjdk11
  - oraclejdk11

matrix:
  allow_failures:
    - jdk: openjdk9
    - jdk: oraclejdk9
    - jdk: openjdk10
    - jdk: oraclejdk10
    - jdk: openjdk11
    - jdk: oraclejdk11
